// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjhaibbnookswzuakgek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqaGFpYmJub29rc3d6dWFrZ2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NTkwNzMsImV4cCI6MjA1NTEzNTA3M30.JbuH0DmkdSEkXaQCkEWGDJc1nipGw4AWPWT7OZpoKPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);